#!/bin/bash

echo "--------------------------------------------------------"
echo "🚧 Verifying build integrity before the commit..."
echo "--------------------------------------------------------"

# -B: Batch mode (less colorful/interactive logs)
# -q: Quiet (prints only errors)
./mvnw -f ./apps/pom.xml clean compile -B -q

EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
    echo " "
    echo "❌ ABORTING THE COMMIT!"
    echo "The project does not compile. Correct the errors and try again."
    echo "--------------------------------------------------------"
    exit 1
else
    echo "✅ Approved compile. Proceeding with the commit."
    echo "--------------------------------------------------------"
    exit 0
fi