#!/bin/bash

echo -e "\e[33m------------------------------------------------\e[0m"
echo -e "\e[33m Verifying build integrity before the commit...\e[0m"
echo -e "\e[33m------------------------------------------------\e[0m\n"

./mvnw clean compile -B -q

EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
  echo -e "\n\e[33m---------------------------------------------------------------\e[0m"
  echo -e "\e[33m ABORTING THE COMMIT!\e[0m"
  echo -e "\e[33mThe project does not compile. Correct the errors and try again.\e[0m"
  echo -e "\e[33m---------------------------------------------------------------\e[0m"
  exit 1
else
  echo -e "\n\e[32m-----------------------------------------------\e[0m"
  echo -e "\e[32m Approved compile. Proceeding with the commit.\e[0m"
  echo -e "\e[32m-----------------------------------------------\e[0m"
  exit 0
fi