services:
  customers_db:
    container_name: biosecure-customers-db
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-customers-db}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  customers_api:
    container_name: biosecure-customers-api
    build:
      context: .
      secrets:
        - maven_settings
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://customers_db:5432/${DB_NAME:-customers-db}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      SPRING_FLYWAY_USER: ${DB_USER}
      SPRING_FLYWAY_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - customers_db

secrets:
  maven_settings:
    file: ${MAVEN_SETTINGS_PATH:-./settings-docker.xml}

volumes:
  postgres_data: