services:
  # --------------------------------
  # CUSTOMER DATA BASE CONFIGS
  # --------------------------------
  customer_data_base:
    image: postgres:17
    container_name: customer_db

    restart: unless-stopped

    environment:
      POSTGRES_USER: ${CUSTOMER_DB_USER}
      POSTGRES_PASSWORD: ${CUSTOMER_DB_PASSWORD}
      POSTGRES_DB: ${CUSTOMER_DB_NAME}

    ports:
      - "5432:5432"
    volumes:
      - customer_data:/var/lib/postgresql/data

  # --------------------------------
  # PRODUCT DATA BASE CONFIGS
  # --------------------------------
  product_data_base:
    image: postgres:17
    container_name: product_db
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${PRODUCT_DB_USER}
      POSTGRES_PASSWORD: ${PRODUCT_DB_PASSWORD}
      POSTGRES_DB: ${PRODUCT_DB_NAME}

    ports:
      - "5433:5432"
    volumes:
      - product_data:/var/lib/postgresql/data

volumes:
  customer_data:
  product_data: