server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: BioSecure - Customers API

  datasource:
    driver-class-name: org.postgresql.Driver

    url: jdbc:postgresql://localhost:5432/${CUSTOMER_DB_NAME}

    username: ${CUSTOMER_DB_USER}
    password: ${CUSTOMER_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: false

    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migrations

    schemas: sales, flyway_history
    default-schema: flyway_history
    create-schemas: true

    user: ${CUSTOMER_DB_USER}
    password: ${CUSTOMER_DB_PASSWORD}